// Prebuilt tasks library
// This file contains a collection of 100 prebuilt tasks across different categories

export const prebuiltTasks = [
  // PRODUCTIVITY & WORK CATEGORY (20 tasks)
  {
    id: "prod-1",
    name: "Deep Work Session",
    description:
      "Schedule a 90-minute focused work session with no distractions. Turn off notifications and focus on your most important task.",
    category: "productivity & work",
    type: "standard",
    isRecurring: true,
    preferredSegmentTime: "09:00", // Morning work segment
  },
  {
    id: "prod-2",
    name: "Email Processing",
    description:
      "Process your inbox to zero using the 2-minute rule: if it takes less than 2 minutes, do it now; otherwise, schedule it.",
    category: "productivity & work",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "prod-3",
    name: "Weekly Planning",
    description: "Review your calendar, projects, and goals to plan your week ahead. Identify your top 3 priorities.",
    category: "productivity & work",
    type: "subtasks",
    isRecurring: true,
    subtasks: [
      "Review last week's accomplishments",
      "Check upcoming calendar events",
      "Identify top 3 priorities for the week",
      "Schedule deep work blocks",
      "Plan buffer time for unexpected tasks",
    ],
  },
  {
    id: "prod-4",
    name: "Daily Review",
    description: "End your workday with a quick review of what you accomplished and what needs to be done tomorrow.",
    category: "productivity & work",
    type: "subtasks",
    isRecurring: true,
    preferredSegmentTime: "16:00", // Afternoon segment
    subtasks: [
      "Review completed tasks",
      "Note any unfinished tasks",
      "Identify top 3 priorities for tomorrow",
      "Clear desk and digital workspace",
      "Write down any lingering thoughts",
    ],
  },
  {
    id: "prod-5",
    name: "Pomodoro Work Session",
    description:
      "Work in focused 25-minute intervals with 5-minute breaks. Complete 4 sessions, then take a longer 15-30 minute break.",
    category: "productivity & work",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "prod-6",
    name: "Meeting Preparation",
    description:
      "Prepare for an upcoming meeting by reviewing the agenda, preparing questions, and gathering necessary materials.",
    category: "productivity & work",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "prod-7",
    name: "Project Status Update",
    description:
      "Review and document the current status of your active projects, noting progress, blockers, and next steps.",
    category: "productivity & work",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "prod-8",
    name: "Desk Organization",
    description: "Clear and organize your physical workspace to improve focus and efficiency.",
    category: "productivity & work",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "prod-9",
    name: "Digital Declutter",
    description:
      "Clean up your digital workspace by organizing files, clearing your desktop, and archiving old emails.",
    category: "productivity & work",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Clean up desktop files",
      "Organize documents folder",
      "Archive old emails",
      "Update bookmarks",
      "Clear downloads folder",
    ],
  },
  {
    id: "prod-10",
    name: "Learning Session",
    description: "Dedicate time to learning a new skill or topic related to your work or interests.",
    category: "productivity & work",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "prod-11",
    name: "Water Breaks",
    description:
      "Take regular water breaks throughout your workday to stay hydrated and give your eyes a rest from screens.",
    category: "productivity & work",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "prod-12",
    name: "Standing Breaks",
    description:
      "If you work at a desk, take regular breaks to stand up, stretch, and move around to prevent stiffness.",
    category: "productivity & work",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "prod-13",
    name: "Task Batching",
    description: "Group similar tasks together and complete them in a single session to reduce context switching.",
    category: "productivity & work",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "prod-14",
    name: "Distraction Audit",
    description: "Track and analyze what distracts you during work to develop strategies for minimizing interruptions.",
    category: "productivity & work",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "prod-15",
    name: "Feedback Collection",
    description: "Actively seek feedback on your work or a specific project to identify areas for improvement.",
    category: "productivity & work",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "prod-16",
    name: "Documentation Update",
    description:
      "Review and update documentation for projects, processes, or knowledge bases to ensure information is current.",
    category: "productivity & work",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "prod-17",
    name: "Skill Practice",
    description: "Dedicate time to deliberately practice and improve a specific skill related to your work.",
    category: "productivity & work",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "prod-18",
    name: "Networking Outreach",
    description:
      "Reach out to colleagues, mentors, or industry contacts to maintain and build professional relationships.",
    category: "productivity & work",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "prod-19",
    name: "Tool Evaluation",
    description: "Research and evaluate new tools or methods that could improve your workflow and productivity.",
    category: "productivity & work",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "prod-20",
    name: "Monthly Review",
    description: "Conduct a comprehensive review of your work, goals, and systems at the end of each month.",
    category: "productivity & work",
    type: "subtasks",
    isRecurring: true,
    subtasks: [
      "Review monthly goals and achievements",
      "Analyze productivity patterns",
      "Identify improvement opportunities",
      "Adjust systems and workflows",
      "Set goals for next month",
    ],
  },

  // HEALTH & FITNESS CATEGORY (15 tasks)
  {
    id: "health-1",
    name: "Morning Stretching Routine",
    description: "Start your day with a 5-10 minute stretching routine to wake up your body and improve flexibility.",
    category: "health & fitness",
    type: "standard",
    isRecurring: true,
    preferredSegmentTime: "06:00", // Morning segment
  },
  {
    id: "health-2",
    name: "Daily Hydration Tracking",
    description: "Track your water intake throughout the day, aiming for 8 glasses or 2 liters.",
    category: "health & fitness",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "health-3",
    name: "Workout Session",
    description: "Complete a structured workout session based on your fitness goals and preferences.",
    category: "health & fitness",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "health-4",
    name: "Meal Planning",
    description: "Plan your meals for the week ahead, focusing on balanced nutrition and variety.",
    category: "health & fitness",
    type: "subtasks",
    isRecurring: true,
    subtasks: [
      "Check pantry and fridge inventory",
      "Plan meals for the week",
      "Create shopping list",
      "Prep ingredients in advance",
      "Schedule cooking times",
    ],
  },
  {
    id: "health-5",
    name: "Step Goal",
    description: "Reach your daily step goal (recommended 7,000-10,000 steps) to maintain basic activity levels.",
    category: "health & fitness",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "health-6",
    name: "Posture Check",
    description: "Take regular moments throughout the day to check and correct your posture, especially when sitting.",
    category: "health & fitness",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "health-7",
    name: "Sleep Hygiene Routine",
    description: "Follow a consistent pre-sleep routine to improve sleep quality and duration.",
    category: "health & fitness",
    type: "subtasks",
    isRecurring: true,
    preferredSegmentTime: "21:00", // Night segment
    subtasks: [
      "Dim lights 1 hour before bed",
      "Avoid screens 30 minutes before sleep",
      "Set comfortable room temperature",
      "Practice relaxation technique",
      "Go to bed at consistent time",
    ],
  },
  {
    id: "health-8",
    name: "Mindful Eating",
    description: "Practice eating without distractions, focusing on the taste, texture, and enjoyment of your food.",
    category: "health & fitness",
    type: "standard",
    isRecurring: true,
    preferredSegmentTime: "12:00", // Lunch segment
  },
  {
    id: "health-9",
    name: "Fitness Progress Tracking",
    description:
      "Record and review your fitness metrics (weight, measurements, performance) to track progress over time.",
    category: "health & fitness",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "health-10",
    name: "Active Recovery",
    description: "Engage in light activity like walking, gentle yoga, or stretching on rest days to promote recovery.",
    category: "health & fitness",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "health-11",
    name: "Healthy Snack Preparation",
    description: "Prepare healthy snacks in advance to have nutritious options readily available when hunger strikes.",
    category: "health & fitness",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "health-12",
    name: "Eye Rest Breaks",
    description:
      "Follow the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds to reduce eye strain.",
    category: "health & fitness",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "health-13",
    name: "Health Metrics Review",
    description:
      "Review your health metrics (blood pressure, resting heart rate, etc.) and note any changes or concerns.",
    category: "health & fitness",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "health-14",
    name: "Outdoor Activity",
    description:
      "Spend time outdoors in natural light, which is beneficial for mood, vitamin D levels, and circadian rhythm.",
    category: "health & fitness",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "health-15",
    name: "Weekly Health Assessment",
    description: "Take time to assess your overall health, energy levels, and well-being each week.",
    category: "health & fitness",
    type: "subtasks",
    isRecurring: true,
    subtasks: [
      "Rate energy levels (1-10)",
      "Note any physical discomfort",
      "Assess sleep quality",
      "Review nutrition patterns",
      "Plan adjustments for next week",
    ],
  },

  // MINDFULNESS & MENTAL HEALTH CATEGORY (12 tasks)
  {
    id: "mind-1",
    name: "Morning Meditation",
    description: "Start your day with a 5-10 minute meditation to center yourself and set a positive tone.",
    category: "mindfulness & mental health",
    type: "standard",
    isRecurring: true,
    preferredSegmentTime: "06:00", // Morning segment
  },
  {
    id: "mind-2",
    name: "Gratitude Practice",
    description: "Write down three things you're grateful for to cultivate a positive mindset and appreciation.",
    category: "mindfulness & mental health",
    type: "standard",
    isRecurring: true,
    preferredSegmentTime: "21:00", // Night segment
  },
  {
    id: "mind-3",
    name: "Mindful Breathing",
    description:
      "Take short breaks throughout the day to practice deep, mindful breathing to reduce stress and increase presence.",
    category: "mindfulness & mental health",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "mind-4",
    name: "Digital Detox",
    description: "Designate time to disconnect from digital devices and engage in screen-free activities.",
    category: "mindfulness & mental health",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "mind-5",
    name: "Mood Tracking",
    description: "Track your mood throughout the day to identify patterns and triggers that affect your mental state.",
    category: "mindfulness & mental health",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "mind-6",
    name: "Stress Management Plan",
    description: "Develop and implement a personalized plan for managing stress in healthy ways.",
    category: "mindfulness & mental health",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Identify main stress triggers",
      "List effective coping strategies",
      "Create emergency stress protocol",
      "Schedule regular stress-relief activities",
      "Identify support resources",
    ],
  },
  {
    id: "mind-7",
    name: "Nature Connection",
    description: "Spend time in nature to reduce stress, improve mood, and enhance mental clarity.",
    category: "mindfulness & mental health",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "mind-8",
    name: "Journaling Session",
    description: "Write freely about your thoughts, feelings, and experiences to process emotions and gain insights.",
    category: "mindfulness & mental health",
    type: "standard",
    isRecurring: true,
    preferredSegmentTime: "21:00", // Night segment
  },
  {
    id: "mind-9",
    name: "Positive Affirmations",
    description: "Practice saying or writing positive affirmations to counter negative self-talk and build confidence.",
    category: "mindfulness & mental health",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "mind-10",
    name: "Worry Time",
    description:
      "Schedule a specific time to address worries, allowing you to set them aside during the rest of your day.",
    category: "mindfulness & mental health",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "mind-11",
    name: "Boundary Setting",
    description: "Identify and enforce healthy boundaries in your personal and professional relationships.",
    category: "mindfulness & mental health",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Identify areas needing boundaries",
      "Define specific boundaries",
      "Practice boundary statements",
      "Implement in low-stress situations first",
      "Reflect on results and adjust",
    ],
  },
  {
    id: "mind-12",
    name: "Weekly Mental Health Check-in",
    description:
      "Take time to check in with yourself about your mental and emotional state, noting any concerns or improvements.",
    category: "mindfulness & mental health",
    type: "standard",
    isRecurring: true,
  },

  // PERSONAL DEVELOPMENT CATEGORY (12 tasks)
  {
    id: "dev-1",
    name: "Reading Session",
    description:
      "Dedicate time to reading books, articles, or other materials that contribute to your knowledge and growth.",
    category: "personal development",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "dev-2",
    name: "Skill Practice",
    description: "Spend time deliberately practicing and developing a specific skill you want to improve.",
    category: "personal development",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "dev-3",
    name: "Goal Review",
    description: "Review your short and long-term goals, assess progress, and make adjustments as needed.",
    category: "personal development",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "dev-4",
    name: "Learning Project",
    description: "Work on a specific project designed to help you learn and apply new skills or knowledge.",
    category: "personal development",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Define project scope and objectives",
      "Identify resources needed",
      "Break down into manageable steps",
      "Schedule regular work sessions",
      "Set completion criteria",
    ],
  },
  {
    id: "dev-5",
    name: "Reflection Time",
    description: "Set aside time to reflect on recent experiences, lessons learned, and insights gained.",
    category: "personal development",
    type: "standard",
    isRecurring: true,
    preferredSegmentTime: "21:00", // Night segment
  },
  {
    id: "dev-6",
    name: "Habit Tracking",
    description:
      "Track your habits to build awareness and accountability for behaviors you want to change or maintain.",
    category: "personal development",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "dev-7",
    name: "Educational Content",
    description: "Consume educational content like podcasts, videos, or courses related to your interests or goals.",
    category: "personal development",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "dev-8",
    name: "Feedback Implementation",
    description: "Actively work on implementing feedback you've received to improve your skills or behaviors.",
    category: "personal development",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "dev-9",
    name: "Values Alignment Check",
    description: "Review how your actions and decisions align with your core values and make adjustments as needed.",
    category: "personal development",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "dev-10",
    name: "Comfort Zone Challenge",
    description: "Intentionally do something outside your comfort zone to promote growth and build confidence.",
    category: "personal development",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "dev-11",
    name: "Personal Mission Statement",
    description: "Create or review your personal mission statement to clarify your purpose and direction.",
    category: "personal development",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Reflect on core values",
      "Identify key roles in life",
      "Define success in each role",
      "Draft mission statement",
      "Review and refine regularly",
    ],
  },
  {
    id: "dev-12",
    name: "Knowledge Sharing",
    description: "Share your knowledge or skills with others through teaching, writing, or mentoring.",
    category: "personal development",
    type: "standard",
    isRecurring: true,
  },

  // RELATIONSHIPS & SOCIAL CATEGORY (10 tasks)
  {
    id: "rel-1",
    name: "Quality Time",
    description: "Spend focused, quality time with important people in your life without distractions.",
    category: "relationships & social",
    type: "standard",
    isRecurring: true,
    preferredSegmentTime: "18:00", // Evening segment
  },
  {
    id: "rel-2",
    name: "Check-in Call",
    description: "Call or message a friend or family member you haven't connected with recently.",
    category: "relationships & social",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "rel-3",
    name: "Active Listening Practice",
    description:
      "Practice active listening skills in your conversations, focusing fully on understanding the other person.",
    category: "relationships & social",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "rel-4",
    name: "Appreciation Expression",
    description:
      "Express genuine appreciation to someone in your life, acknowledging specific things you value about them.",
    category: "relationships & social",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "rel-5",
    name: "Conflict Resolution",
    description:
      "Address and work through a conflict or misunderstanding in a relationship using healthy communication.",
    category: "relationships & social",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Identify the core issue",
      "Consider the other perspective",
      "Plan conversation approach",
      "Have the conversation",
      "Follow up and check understanding",
    ],
  },
  {
    id: "rel-6",
    name: "Social Event Planning",
    description: "Plan and organize a social gathering or activity to connect with friends or family.",
    category: "relationships & social",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Choose date and activity",
      "Create guest list",
      "Send invitations",
      "Prepare logistics",
      "Follow up with attendees",
    ],
  },
  {
    id: "rel-7",
    name: "Relationship Assessment",
    description:
      "Take time to assess the health and quality of your key relationships and identify areas for improvement.",
    category: "relationships & social",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "rel-8",
    name: "Random Act of Kindness",
    description: "Perform an unexpected act of kindness for someone in your life or a stranger.",
    category: "relationships & social",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "rel-9",
    name: "Boundary Practice",
    description: "Practice setting and maintaining healthy boundaries in your relationships.",
    category: "relationships & social",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "rel-10",
    name: "Community Engagement",
    description: "Participate in community activities, volunteer work, or group events to build social connections.",
    category: "relationships & social",
    type: "standard",
    isRecurring: true,
  },

  // HOME & ENVIRONMENT CATEGORY (10 tasks)
  {
    id: "home-1",
    name: "Quick Cleaning Session",
    description: "Spend 15-30 minutes on focused cleaning or tidying of a specific area in your home.",
    category: "home & environment",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "home-2",
    name: "Weekly Home Maintenance",
    description: "Complete regular home maintenance tasks to keep your living space functional and comfortable.",
    category: "home & environment",
    type: "subtasks",
    isRecurring: true,
    subtasks: [
      "Clean kitchen thoroughly",
      "Vacuum and mop floors",
      "Change bed linens",
      "Do laundry",
      "Take out all trash and recycling",
    ],
  },
  {
    id: "home-3",
    name: "Decluttering Session",
    description: "Focus on decluttering a specific area, drawer, or category of items in your home.",
    category: "home & environment",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "home-4",
    name: "Plant Care",
    description: "Check on and care for your houseplants, including watering, pruning, and inspecting for issues.",
    category: "home & environment",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "home-5",
    name: "Seasonal Home Maintenance",
    description: "Complete seasonal maintenance tasks appropriate for the current time of year.",
    category: "home & environment",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Check smoke/CO detectors",
      "Clean gutters/vents",
      "Inspect for needed repairs",
      "Seasonal equipment maintenance",
      "Adjust for seasonal needs",
    ],
  },
  {
    id: "home-6",
    name: "Sustainable Practice",
    description:
      "Implement or improve a sustainable practice in your home, such as composting, reducing waste, or conserving energy.",
    category: "home & environment",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "home-7",
    name: "Home Improvement Project",
    description: "Work on a specific home improvement or decoration project to enhance your living space.",
    category: "home & environment",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Plan project scope and budget",
      "Gather necessary supplies",
      "Prepare the space",
      "Complete the main work",
      "Clean up and finalize",
    ],
  },
  {
    id: "home-8",
    name: "Digital Home Organization",
    description:
      "Organize digital aspects of home management, such as bills, important documents, or family calendars.",
    category: "home & environment",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "home-9",
    name: "Meal Preparation",
    description: "Prepare meals or components in advance to save time and ensure healthy eating throughout the week.",
    category: "home & environment",
    type: "standard",
    isRecurring: true,
    preferredSegmentTime: "12:00", // Lunch segment
  },
  {
    id: "home-10",
    name: "Home Inventory Check",
    description: "Review inventory of household essentials and create a shopping list for needed items.",
    category: "home & environment",
    type: "standard",
    isRecurring: true,
  },

  // CAREER & PROFESSIONAL CATEGORY (11 tasks)
  {
    id: "career-1",
    name: "Professional Development",
    description: "Engage in learning activities specifically related to your career or professional goals.",
    category: "career & professional",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "career-2",
    name: "Resume/Portfolio Update",
    description: "Review and update your resume, CV, or professional portfolio with recent accomplishments and skills.",
    category: "career & professional",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "career-3",
    name: "Networking Activity",
    description: "Engage in professional networking through events, online platforms, or one-on-one connections.",
    category: "career & professional",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "career-4",
    name: "Career Planning Session",
    description: "Review and update your career plan, including short and long-term goals and action steps.",
    category: "career & professional",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Assess current position and skills",
      "Research industry trends",
      "Define 1-year and 5-year goals",
      "Identify skill gaps to address",
      "Create action plan with milestones",
    ],
  },
  {
    id: "career-5",
    name: "Industry Research",
    description: "Stay current on your industry by researching trends, news, and developments.",
    category: "career & professional",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "career-6",
    name: "Professional Reading",
    description: "Read books, articles, or journals related to your field or professional interests.",
    category: "career & professional",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "career-7",
    name: "Skill Development",
    description: "Work on developing a specific skill that will enhance your professional capabilities.",
    category: "career & professional",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "career-8",
    name: "Performance Review Preparation",
    description: "Prepare for an upcoming performance review by documenting achievements and areas for growth.",
    category: "career & professional",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "List key accomplishments",
      "Gather performance metrics",
      "Identify growth opportunities",
      "Prepare questions",
      "Set goals for discussion",
    ],
  },
  {
    id: "career-9",
    name: "Professional Organization Engagement",
    description: "Participate in activities or events with professional organizations in your field.",
    category: "career & professional",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "career-10",
    name: "Mentor/Mentee Meeting",
    description: "Schedule and prepare for a meeting with your mentor or mentee to exchange insights and guidance.",
    category: "career & professional",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "career-11",
    name: "Work-Life Balance Assessment",
    description: "Evaluate your current work-life balance and identify adjustments needed for better integration.",
    category: "career & professional",
    type: "standard",
    isRecurring: false,
  },

  // CREATIVITY & HOBBIES CATEGORY (10 tasks)
  {
    id: "creative-1",
    name: "Creative Practice Session",
    description: "Dedicate time to practicing a creative hobby or skill, such as drawing, writing, music, or crafting.",
    category: "creativity & hobbies",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "creative-2",
    name: "Inspiration Collection",
    description: "Gather and organize inspiration for creative projects from various sources.",
    category: "creativity & hobbies",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "creative-3",
    name: "Creative Project Work",
    description: "Work on a specific creative project you're developing, breaking it down into manageable steps.",
    category: "creativity & hobbies",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Define project vision and goals",
      "Gather necessary materials",
      "Complete initial draft/sketch",
      "Refine and improve",
      "Finalize and share/display",
    ],
  },
  {
    id: "creative-4",
    name: "Skill Exploration",
    description: "Try a new creative technique or approach to expand your skills and perspective.",
    category: "creativity & hobbies",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "creative-5",
    name: "Creative Community Engagement",
    description: "Participate in a community of fellow creators through classes, groups, or online forums.",
    category: "creativity & hobbies",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "creative-6",
    name: "Hobby Equipment Maintenance",
    description: "Clean, organize, and maintain the tools and equipment related to your hobbies.",
    category: "creativity & hobbies",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "creative-7",
    name: "Creative Consumption",
    description: "Intentionally consume creative works that inspire and inform your own creative practice.",
    category: "creativity & hobbies",
    type: "tally",
    isRecurring: true,
  },
  {
    id: "creative-8",
    name: "Skill Sharing",
    description: "Share your creative skills or knowledge with others through teaching or demonstration.",
    category: "creativity & hobbies",
    type: "standard",
    isRecurring: false,
  },
  {
    id: "creative-9",
    name: "Creative Challenge",
    description: "Take on a specific creative challenge or prompt to push your skills and imagination.",
    category: "creativity & hobbies",
    type: "standard",
    isRecurring: true,
  },
  {
    id: "creative-10",
    name: "Portfolio Development",
    description: "Organize and present your creative work in a portfolio format, whether physical or digital.",
    category: "creativity & hobbies",
    type: "subtasks",
    isRecurring: false,
    subtasks: [
      "Select best work samples",
      "Organize by theme or chronology",
      "Write descriptions/artist statements",
      "Create presentation format",
      "Get feedback and refine",
    ],
  },
]
