diff --git a/docs/bundle-analysis.md b/docs/bundle-analysis.md
index b5d86ab21baac505bb9d9fa483a64c9f1a71b2e6..3a9a3a514ef934eb2a980c17d7301695ded6214f 100644
--- a/docs/bundle-analysis.md
+++ b/docs/bundle-analysis.md
@@ -36,33 +36,26 @@ The bundle analyzer generates an interactive treemap visualization:
 2. **Import Only What You Need**: Instead of importing entire libraries
    \`\`\`jsx
    // Bad
    import * as LucideIcons from 'lucide-react';
    
    // Good
    import { Clock, Calendar } from 'lucide-react';
    \`\`\`
 
 3. **Optimize Images**: Use Next.js Image component with proper sizing
    \`\`\`jsx
    import Image from 'next/image';
    
    <Image 
      src="/image.jpg" 
      width={400} 
      height={300} 
      alt="Description" 
    />
    \`\`\`
 
 4. **Use Code Splitting**: Next.js automatically splits code by pages, but you can further optimize with dynamic imports
 
 ## Vercel Deployment
 
-When deploying to Vercel, the optimizations in `next.config.mjs` will automatically apply:
-
-- Console logs removal in production
-- CSS optimization
-- Package import optimization
-- Code splitting
-
-No additional environment variables are needed for your Vercel deployment.
+Deploying to Vercel uses the same configuration defined in `next.config.mjs`. No additional environment variables are required.
